---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disable-service-account-token-automount
  annotations:
    policies.kyverno.io/title: Disable Service Account Token Automount
    policies.kyverno.io/category: RBAC
    policies.kyverno.io/severity: medium
spec:
  admission: true
  background: true
  validationFailureAction: Enforce
  rules:
    - name: validate-token-automount
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaceSelector:
                matchLabels:
                  security.platform.io/enforce: restricted
      validate:
        allowExistingViolations: true
        message: Service account token automount must be disabled.
        pattern:
          spec:
            automountServiceAccountToken: false
