---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: drop-linux-capabilities
  annotations:
    policies.kyverno.io/title: Drop Linux Capabilities
    policies.kyverno.io/category: Pod Security Standards
    policies.kyverno.io/severity: high
spec:
  admission: true
  background: true
  validationFailureAction: Enforce
  rules:
    - name: require-drop-all
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaceSelector:
                matchLabels:
                  security.platform.io/enforce: restricted
      validate:
        allowExistingViolations: true
        message: Containers must drop all Linux capabilities.
        pattern:
          spec:
            containers:
              - securityContext:
                  capabilities:
                    drop:
                      - ALL
            =(initContainers):
              - securityContext:
                  capabilities:
                    drop:
                      - ALL
            =(ephemeralContainers):
              - securityContext:
                  capabilities:
                    drop:
                      - ALL
