---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-seccomp
  annotations:
    policies.kyverno.io/title: Require Seccomp
    policies.kyverno.io/category: Pod Security Standards
    policies.kyverno.io/severity: high
spec:
  admission: true
  background: true
  validationFailureAction: Enforce
  rules:
    - name: validate-seccomp
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaceSelector:
                matchLabels:
                  security.platform.io/enforce: restricted
      validate:
        allowExistingViolations: true
        message: Pods must use RuntimeDefault or Localhost seccomp profiles.
        pattern:
          spec:
            securityContext:
              seccompProfile:
                type: "RuntimeDefault | Localhost"
