---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-read-only-root-filesystem
  annotations:
    policies.kyverno.io/title: Require Read-only Root Filesystem
    policies.kyverno.io/category: Pod Security Standards
    policies.kyverno.io/severity: medium
spec:
  admission: true
  background: true
  validationFailureAction: Enforce
  rules:
    - name: validate-read-only-root-filesystem
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaceSelector:
                matchLabels:
                  security.platform.io/enforce: restricted
      validate:
        allowExistingViolations: true
        message: Containers must use a read-only root filesystem.
        pattern:
          spec:
            containers:
              - securityContext:
                  readOnlyRootFilesystem: true
            =(initContainers):
              - securityContext:
                  readOnlyRootFilesystem: true
