---
apiVersion: v1
kind: Secret
metadata:
  name: example-application-secret
  namespace: platform-secrets
  labels:
    app.kubernetes.io/name: example-application-secret
    app.kubernetes.io/part-of: k8s-platform-foundation
    app.kubernetes.io/managed-by: sops
type: Opaque
stringData:
  username: replace-me
  password: replace-me
