---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-production

resources:
  - policy.yaml
  - pdb.yaml
  - ../base

nameSuffix: -production

labels:
  - pairs:
      app.kubernetes.io/environment: production
    includeSelectors: false

patches:
  - target:
      kind: Namespace
      name: platform-workloads
    patch: |-
      - op: replace
        path: /metadata/name
        value: platform-production

  - target:
      kind: Deployment
      name: platform-demo
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
