---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: platform-demo
  namespace: platform-production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-demo
