---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
  labels:
    app.kubernetes.io/name: cloudflare-api-token
    app.kubernetes.io/part-of: k8s-platform-foundation
    app.kubernetes.io/managed-by: sops
type: Opaque
stringData:
  apiToken: replace-me
