---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-foundation
    - name: encrypted-secrets

  interval: 10m
  retryInterval: 1m
  timeout: 10m
  wait: true
  prune: true

  sourceRef:
    kind: GitRepository
    name: k8s-platform-foundation

  path: ./platform/external-dns

  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: external-dns
      namespace: external-dns
