---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flagger
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-foundation
    - name: observability
    - name: external-dns

  interval: 10m
  retryInterval: 1m
  timeout: 15m
  wait: true
  prune: true

  sourceRef:
    kind: GitRepository
    name: k8s-platform-foundation

  path: ./platform/flagger

  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: flagger
      namespace: flagger-system

    - apiVersion: apps/v1
      kind: Deployment
      name: flagger-loadtester
      namespace: flagger-system
