---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security-controller
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 15m
  wait: true
  prune: true

  sourceRef:
    kind: GitRepository
    name: k8s-platform-foundation

  path: ./security/kyverno

  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno-admission-controller
      namespace: kyverno

    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno-background-controller
      namespace: kyverno
