name: kube-linter

on:
  pull_request:
  push:
    branches: [main]

jobs:
  kube-linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: stackrox/kube-linter-action@v1
