---
name: markdownlint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v24
