name: shfmt

on:
  pull_request:
  push:
    branches: [main]

jobs:
  shfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - run: |
          docker run --rm \
            -v "$PWD:/mnt" \
            mvdan/shfmt:latest \
            -d /mnt
